# This is a TOML document

[menu]
pointer = ">"
welcome_message = "Hello and welcome choose an option:"
[json]
json_file_name = "alarms.json"
[logger]
folder_icon = "ğŸ“"
alarm_icon = "ó°"
json_icon = "ğŸ‘º"
initalize_icon = "ğŸŒŸ"
date_format = "%d/%m/%Y %H:%M:%S" # default
# date_format = "%d/%m/%Y"
log_save_path = "./"
log_name = "log.txt"
log_spacing = " ğŸ¥ŠğŸ¥ŠğŸ¥Š " # works
